### ISSUE TITLE
DS-Xtreme support...

### ISSUE THREAD

**Issue by ApacheThunder** [kitling/ak2itool#1]
This might fall outside the scope of this tool maybe but I happen to own a DS-Xtreme. This tool or something like it could support writing custom firmware to it. 

This card card was initially documented here:

https://wiki.gbatemp.net/wiki/DS-Xtreme

However it seems whom ever was looking at the flasher for this device stopped for unknown reasons. A while back while I was making launchers for various flashcarts to use with 3DS I found the firmware files and the updaters for them. The ones I have are slightly modified so as to not require getting the firmware files off a URL and instead get them off locally:

http://www.battlefieldsingleplayer.com/apachethunder/3ds/TWL/DSX/DSX_Updaters.rar

Since this card has it's own USB port and drivers perhaps this could be supported? But since it was meant to be flashed from it's own USB port, it may not fall in the scope of this tool. Still though it would be nice to see something done with this card. I happen to own one and can test anything you might manage to make for it.

**Comment by kitlith** [comment]
This is designed for cards that you flash using the DS, using cartridge commands to write the flash, not for cartridges you flash over USB. Depending on how it works, this would be more in line for a libpowerslaves type library than this tool, but I don't know.

Looking at the wiki article, it doesn't appear to give too much detail, either. If it said that it communicates over USB HID, and here are the commands it uses, that would've been nice. I could've worked something out with hidapi like I do for powersaves for another tool/library. The Open Source project also isn't of much help, as it seems nobody actually dumped the knowledge of what's going on somewhere? 

Closing as out-of-scope, as you suspected. I don't see myself working on this anytime soon, but thank you for bringing it up! I *might* take a look at it another time. And thank you for taking the time to bring it up! Feel free to create issues for any other cards you might have.

I guess I'll leave some additional thoughts for the future here:
 - It does not appear to need drivers installed for the updater to interact. Interacts over HID, just like powersaves? Would make life a whole lot easier if so. No driver hell!
 - Contains a confusingly named "ProASIC 3" FPGA. bitstream is updatable? It's not gonna be reverse engineered, because lol decompiling bitstreams, but we could find which pins are assigned to what, and reimplement from there, if we really wanted to take the time to do that.

**Comment by ApacheThunder** [comment]
Yeah it appears to use standard drivers. I don't recall having to install custom drivers. It does have drivers for recovery mode? But normal operation doesn't require them.

Yeah one day I'd like to see something done with this. For one the NTR rom it presents to the console is...weird. It has it's arm9 binary at some high offset that is non standard and uses an arm7 code/ram entry address newer consoles like DSi and 3DS don't like (though on 3DS CFW can be used to run custom DSiWare that can be used to launch said cards bypassing TWL_FIRM's protections). Due to a mess up Nintendo did with the DS Cart White list on 1.4 firmware on DSi (they forgot to implement RSA checks for it lol), I can create custom entries and white list any cart I like. I successfully did this with my CodeBreaker cart (Action Replay clone. Internal rom is custom and does not spoof any game) but the cart still has to play nice in terms of the arm7 settings. :P

Yeah perhaps the DS-X could be a separate project in the future. Thought I'd bring up because maybe it could be used for things like sighax backdoor. But you would definitely have to RE the FPGA side of the card to change the blowfish keys it uses most likely. :(

Right now it's the only cart besides a non SDHC R4 clone. It looks like an original R4 an acts like one (mostly?) but is most definitely a clone. I used to own a Gateway Blue Cart and a DSTT but have long sold them off.

I can try and get an Acekard but I have a feeling the prices for them will skyrocket by the time I have the money to get one. (or simply be out of stock everywhere)

**Comment by kitlith** [comment]
Again, Reverse Engineering of the FPGA imost likely isn't going to happen. This is due to the highly vendor-dependant bitstream formats and the NP nature of circuit design. However, we could get ahold of the ProASIC tools, and after figuring out the pinout, reimplement parts of it.

**Comment by ApacheThunder** [comment]
Just to post a long overdue update on this. I eventually figured out how to access the hidden section of NAND and can alter the arm binaries and banner the primary rom section uses (check out dsxTool on my Github that allows messing with this stuff. :D ).

BUT the SRL header is no where to be found. Blowfish key and header is likely hardcoded into the FPGA firmware somehow or on a SPI flash chip (but I'm not aware of one this cart uses besides the one used for saves)....Because of this, the custom bootstrap I have flashed to the card had to be compiled to use the entry points the original header used and arm binaries that fit withen the originally defined sizes the header setup. (not too hard as it assigns a very large value for the arm9 binary. Even Unlaunch has trouble booting it because of that. :P )

Not a big issue but it does prevent changing the blowfish key and what not as that doesn't appear to be in the hidden section of nand.

So yeah this is likely never gonna be a thing with this card. :(
